apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: alertmanager-proxy-cert
  labels:
    app: enmasse
spec:
  ports:
  - name: alertmanager
    port: 9093
    targetPort: 9093
  - name: proxy
    port: 443
    targetPort: 8443
  selector:
    name: alertmanager
