apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: enmasse
  name: prometheus-server
  annotations: 
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"prometheus"}}'
