---
- name: Create secret with the keycloak credentials
  shell: oc create secret generic -n {{ namespace }} keycloak-credentials --from-literal=admin.username=admin --from-literal=admin.password={{ keycloak_admin_password }}
  register: secret_exists
  failed_when: secret_exists.stderr != '' and 'already exists' not in secret_exists.stderr
- name: Apply the Standard Authentication Service configuration
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/install/standard-authservice
