apiVersion: v1
kind: ConfigMap
metadata:
  name: standard-infra-config-with-mqtt
  labels:
    type: standard-infra-config
    app: enmasse
data:
  definition: |-
    {
      "apiVersion": "admin.enmasse.io/v1alpha1",
      "kind": "StandardInfraconfig",
      "metadata": {
        "name": "standard-infra-config-with-mqtt",
        "annotations": {
          "enmasse.io/template-name": "standard-space-infra",
          "enmasse.io/mqtt-template-name": "standard-space-infra-mqtt",
          "enmasse.io/queue-template-name": "queue-persisted",
          "enmasse.io/topic-template-name": "topic-persisted"
        }
      },
      "spec": {
        "version": "${ENMASSE_VERSION}",
        "admin": {
          "resources": {
            "memory": "512Mi"
          }
        },
        "broker": {
          "resources": {
            "memory": "512Mi",
            "storage": "2Gi"
          },
          "addressFullPolicy": "FAIL"
        },
        "router": {
          "resources": {
            "memory": "512Mi"
          },
          "linkCapacity": "250"
        }
      }
    }
