apiVersion: v1
kind: ConfigMap
metadata:
  name: brokered-infra-config
  labels:
    type: brokered-infra-config
    app: enmasse
data:
  definition: |-
    {
      "apiVersion": "admin.enmasse.io/v1alpha1",
      "kind": "BrokeredInfraConfig",
      "metadata": {
        "name": "brokered-infra-config",
        "annotations": {
          "enmasse.io/template-name": "brokered-space-infra"
        }
      },
      "spec": {
        "version": "${ENMASSE_VERSION}",
        "admin": {
          "resources": {
            "memory": "512Mi"
          }
        },
        "broker": {
          "resources": {
            "memory": "512Mi",
            "storage": "5Gi"
          },
          "addressFullPolicy": "FAIL"
        }
      }
    }
