apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enmasse.io:keycloak-controller
rules:
  - apiGroups: [ "", "user.openshift.io" ]
    resources: [ "users" ]
    verbs: [ "get" ]
