---
- name: Extract API Server CA
  shell: oc extract secret/api-server-cert -n {{ namespace }} --keys=tls.crt --to=-
  until: secret_result.rc == 0
  retries: 10
  delay: 5
  register: secret_result

- set_fact:
    ca_bundle: "{{ secret_result.stdout }}"

- name: Register API Server with API Aggregator
  shell:
    cmd: |
      cat <<EOF | oc apply -f -
      apiVersion: apiregistration.k8s.io/v1beta1
      kind: APIService
      metadata:
        name: v1alpha1.enmasse.io
      spec:
        group: enmasse.io
        groupPriorityMinimum: 1000
        caBundle: "{{ ca_bundle | b64encode }}"
        version: v1alpha1
        versionPriority: 10
        service:
          name: api-server
          namespace: "{{ namespace }}"
      EOF

- name: Register User API Server with API Aggregator
  when: '"standard" in authentication_services'
  shell:
    cmd: |
      cat <<EOF | oc apply -f -
      apiVersion: apiregistration.k8s.io/v1beta1
      kind: APIService
      metadata:
        name: v1alpha1.user.enmasse.io
      spec:
        group: user.enmasse.io
        groupPriorityMinimum: 1000
        caBundle: "{{ ca_bundle | b64encode }}"
        version: v1alpha1
        versionPriority: 10
        service:
          name: api-server
          namespace: "{{ namespace }}"
      EOF
