apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: enmasse
  name: keycloak
spec:
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: enmasse
      name: keycloak
  template:
    metadata:
      labels:
        app: enmasse
        name: keycloak
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-role.enmasse.io/operator-infra
                    operator: In
                    values:
                      - "true"
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Dvertx.cacheDirBase=/tmp -Djboss.bind.address=0.0.0.0 -Djava.net.preferIPv4Stack=true -Duser.timezone=UTC
            -Xms512m -Xmx1024m
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              key: admin.username
              name: keycloak-credentials
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin.password
              name: keycloak-credentials
        - name: KEYCLOAK_SASL_XOAUTH_BASE_URI
          valueFrom:
            configMapKeyRef:
              key: oauthUrl
              name: keycloak-config
              optional: true
        image: ${KEYCLOAK_IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        livenessProbe:
          httpGet:
            path: /auth
            port: https
            scheme: HTTPS
          initialDelaySeconds: 120
        name: keycloak
        ports:
        - containerPort: 5671
          name: amqps
        - containerPort: 8443
          name: https
        readinessProbe:
          httpGet:
            path: /auth
            port: https
            scheme: HTTPS
          initialDelaySeconds: 60
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 2Gi
        volumeMounts:
        - mountPath: /opt/jboss/keycloak/providers
          name: keycloak-providers
          readOnly: false
        - mountPath: /opt/jboss/keycloak/standalone/configuration
          name: keycloak-configuration
          readOnly: false
        - mountPath: /opt/enmasse/cert
          name: standard-authservice-cert
          readOnly: false
        - mountPath: /opt/jboss/keycloak/standalone/data
          name: keycloak-persistence
          readOnly: false
      initContainers:
      - env:
        - name: KEYCLOAK_DIR
          value: /opt/jboss/keycloak
        image: ${KEYCLOAK_PLUGIN_IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        name: keycloak-plugin
        volumeMounts:
        - mountPath: /opt/jboss/keycloak/providers
          name: keycloak-providers
          readOnly: false
        - mountPath: /opt/jboss/keycloak/standalone/configuration
          name: keycloak-configuration
          readOnly: false
        - mountPath: /opt/enmasse/cert
          name: standard-authservice-cert
          readOnly: false
      serviceAccountName: standard-authservice
      volumes:
      - name: standard-authservice-cert
        secret:
          secretName: standard-authservice-cert
      - name: keycloak-persistence
        persistentVolumeClaim:
          claimName: keycloak-data
      - emptyDir: {}
        name: keycloak-configuration
      - emptyDir: {}
        name: keycloak-providers
